import 'package:flutter/material.dart';
import 'package:yandex_maps_mapkit_lite/init.dart' as init;

import 'map/mapkit_main.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List resultMap = [
    {
      "id": "maajid_hotel",
      "hid": 8911981,
      "rates": [
        {
          "match_hash": "m-41c4f965-da0b-5613-9222-abc42968acdd",
          "search_hash": null,
          "daily_prices": ["3974.00", "3974.00", "3974.00"],
          "meal": "nomeal",
          "meal_data": {
            "value": "nomeal",
            "has_breakfast": false,
            "no_child_meal": true,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "141.63",
                "show_amount": "11922.00",
                "currency_code": "USD",
                "show_currency_code": "RUB",
                "by": null,
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "hotel",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "1818.61",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": "2025-03-25T10:00:00",
                      "amount_charge": "0.00",
                      "amount_show": "0.00",
                    },
                    {
                      "start_at": "2025-03-25T10:00:00",
                      "end_at": null,
                      "amount_charge": "141.63",
                      "amount_show": "11922.00",
                    },
                  ],
                  "free_cancellation_before": "2025-03-25T10:00:00",
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 1,
            "sex": 0,
            "bathroom": 2,
            "bedding": 3,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Economy (двуспальная кровать)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": false,
          "deposit": null,
          "no_show": null,
          "room_data_trans": {
            "main_room_type": "Двухместный номер Economy",
            "main_name": "Двухместный номер Economy",
            "bathroom": null,
            "bedding_type": "двуспальная кровать",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-e19a3f59-6d28-53cf-bc8b-66ec30ab620e",
          "search_hash": null,
          "daily_prices": ["4413.00", "4413.00", "4413.00"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "267.30",
                "show_amount": "13239.00",
                "currency_code": "AZN",
                "show_currency_code": "RUB",
                "by": null,
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "hotel",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2019.51",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": null,
                      "amount_charge": "267.30",
                      "amount_show": "13239.00",
                    },
                  ],
                  "free_cancellation_before": null,
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 1,
            "sex": 0,
            "bathroom": 2,
            "bedding": 3,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Economy (двуспальная кровать)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "267.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Economy",
            "main_name": "Двухместный номер Economy",
            "bathroom": null,
            "bedding_type": "двуспальная кровать",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-8f43ac37-52be-50f0-975f-73fbe14d3ef8",
          "search_hash": null,
          "daily_prices": ["4413.32", "4413.32", "4413.32"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "13239.96",
                "show_amount": "13239.96",
                "currency_code": "RUB",
                "show_currency_code": "RUB",
                "by": "credit_card",
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "now",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2019.65",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": null,
                      "amount_charge": "13239.96",
                      "amount_show": "13239.96",
                    },
                  ],
                  "free_cancellation_before": null,
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 1,
            "sex": 0,
            "bathroom": 2,
            "bedding": 3,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Economy (двуспальная кровать)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "267.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Economy",
            "main_name": "Двухместный номер Economy",
            "bathroom": null,
            "bedding_type": "двуспальная кровать",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-47780c14-f359-577c-b9a9-758e7e370bb3",
          "search_hash": null,
          "daily_prices": ["4457.67", "4457.67", "4457.67"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "270.00",
                "show_amount": "13373.00",
                "currency_code": "AZN",
                "show_currency_code": "RUB",
                "by": null,
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "hotel",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2039.95",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": "2025-03-25T10:00:00",
                      "amount_charge": "0.00",
                      "amount_show": "0.00",
                    },
                    {
                      "start_at": "2025-03-25T10:00:00",
                      "end_at": null,
                      "amount_charge": "270.00",
                      "amount_show": "13373.00",
                    },
                  ],
                  "free_cancellation_before": "2025-03-25T10:00:00",
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 1,
            "sex": 0,
            "bathroom": 2,
            "bedding": 3,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Economy (двуспальная кровать)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "90.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Economy",
            "main_name": "Двухместный номер Economy",
            "bathroom": null,
            "bedding_type": "двуспальная кровать",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-3051492d-01c0-50f7-be53-99c87a0a5d22",
          "search_hash": null,
          "daily_prices": ["4457.90", "4457.90", "4457.90"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "13373.70",
                "show_amount": "13373.70",
                "currency_code": "RUB",
                "show_currency_code": "RUB",
                "by": "credit_card",
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "now",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2040.06",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": "2025-03-25T10:00:00",
                      "amount_charge": "0.00",
                      "amount_show": "0.00",
                    },
                    {
                      "start_at": "2025-03-25T10:00:00",
                      "end_at": null,
                      "amount_charge": "13373.70",
                      "amount_show": "13373.70",
                    },
                  ],
                  "free_cancellation_before": "2025-03-25T10:00:00",
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 1,
            "sex": 0,
            "bathroom": 2,
            "bedding": 3,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Economy (двуспальная кровать)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "90.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Economy",
            "main_name": "Двухместный номер Economy",
            "bathroom": null,
            "bedding_type": "двуспальная кровать",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-0248816e-7dfd-59bc-9bac-25d98bf72224",
          "search_hash": null,
          "daily_prices": ["4953.07", "4953.07", "3813.86"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "277.00",
                "show_amount": "13720.00",
                "currency_code": "AZN",
                "show_currency_code": "RUB",
                "by": null,
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "hotel",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2092.88",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": "2025-03-24T10:00:00",
                      "amount_charge": "0.00",
                      "amount_show": "0.00",
                    },
                    {
                      "start_at": "2025-03-24T10:00:00",
                      "end_at": null,
                      "amount_charge": "277.00",
                      "amount_show": "13720.00",
                    },
                  ],
                  "free_cancellation_before": "2025-03-24T10:00:00",
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 2,
            "sex": 0,
            "bathroom": 2,
            "bedding": 3,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 5,
            "floor": 0,
          },
          "room_name":
              "Двухместный номер Standard с видом на город (двуспальная кровать)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 3,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "100.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Standard с видом на город",
            "main_name": "Двухместный номер Standard с видом на город",
            "bathroom": null,
            "bedding_type": "двуспальная кровать",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-9e44fb7c-b9c5-5f8b-95cb-fb05af68f6e6",
          "search_hash": null,
          "daily_prices": ["4953.22", "4953.22", "3813.98"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "13720.42",
                "show_amount": "13720.42",
                "currency_code": "RUB",
                "show_currency_code": "RUB",
                "by": "credit_card",
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "now",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2092.95",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": "2025-03-24T10:00:00",
                      "amount_charge": "0.00",
                      "amount_show": "0.00",
                    },
                    {
                      "start_at": "2025-03-24T10:00:00",
                      "end_at": null,
                      "amount_charge": "13720.42",
                      "amount_show": "13720.42",
                    },
                  ],
                  "free_cancellation_before": "2025-03-24T10:00:00",
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 2,
            "sex": 0,
            "bathroom": 2,
            "bedding": 3,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 5,
            "floor": 0,
          },
          "room_name":
              "Двухместный номер Standard с видом на город (двуспальная кровать)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 3,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "100.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Standard с видом на город",
            "main_name": "Двухместный номер Standard с видом на город",
            "bathroom": null,
            "bedding_type": "двуспальная кровать",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-6d8b56d8-6489-5528-8514-edf12c900824",
          "search_hash": null,
          "daily_prices": ["5393.78", "5148.61", "5148.61"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "316.80",
                "show_amount": "15691.00",
                "currency_code": "AZN",
                "show_currency_code": "RUB",
                "by": null,
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "hotel",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2393.54",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": null,
                      "amount_charge": "316.80",
                      "amount_show": "15691.00",
                    },
                  ],
                  "free_cancellation_before": null,
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 2,
            "sex": 0,
            "bathroom": 2,
            "bedding": 4,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Standard (2 отдельные кровати)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "316.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Standard",
            "main_name": "Двухместный номер Standard",
            "bathroom": null,
            "bedding_type": "2 отдельные кровати",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-72387d86-649f-5441-a504-f66489367121",
          "search_hash": null,
          "daily_prices": ["5394.06", "5148.88", "5148.88"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "15691.81",
                "show_amount": "15691.81",
                "currency_code": "RUB",
                "show_currency_code": "RUB",
                "by": "credit_card",
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "now",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2393.67",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": null,
                      "amount_charge": "15691.81",
                      "amount_show": "15691.81",
                    },
                  ],
                  "free_cancellation_before": null,
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 2,
            "sex": 0,
            "bathroom": 2,
            "bedding": 4,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Standard (2 отдельные кровати)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "316.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Standard",
            "main_name": "Двухместный номер Standard",
            "bathroom": null,
            "bedding_type": "2 отдельные кровати",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-f1ab84d7-998e-516a-b0cf-66530ea19810",
          "search_hash": null,
          "daily_prices": ["5448.44", "5200.78", "5200.78"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "320.00",
                "show_amount": "15850.00",
                "currency_code": "AZN",
                "show_currency_code": "RUB",
                "by": null,
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "hotel",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2417.80",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": "2025-03-24T10:00:00",
                      "amount_charge": "0.00",
                      "amount_show": "0.00",
                    },
                    {
                      "start_at": "2025-03-24T10:00:00",
                      "end_at": null,
                      "amount_charge": "320.00",
                      "amount_show": "15850.00",
                    },
                  ],
                  "free_cancellation_before": "2025-03-24T10:00:00",
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 2,
            "sex": 0,
            "bathroom": 2,
            "bedding": 4,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Standard (2 отдельные кровати)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "110.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Standard",
            "main_name": "Двухместный номер Standard",
            "bathroom": null,
            "bedding_type": "2 отдельные кровати",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-412f54e1-cbf8-532f-a16e-625bcdd66c11",
          "search_hash": null,
          "daily_prices": ["5448.54", "5200.88", "5200.88"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "15850.31",
                "show_amount": "15850.31",
                "currency_code": "RUB",
                "show_currency_code": "RUB",
                "by": "credit_card",
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "now",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "12.00",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2417.84",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": "2025-03-24T10:00:00",
                      "amount_charge": "0.00",
                      "amount_show": "0.00",
                    },
                    {
                      "start_at": "2025-03-24T10:00:00",
                      "end_at": null,
                      "amount_charge": "15850.31",
                      "amount_show": "15850.31",
                    },
                  ],
                  "free_cancellation_before": "2025-03-24T10:00:00",
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 2,
            "sex": 0,
            "bathroom": 2,
            "bedding": 4,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Standard (2 отдельные кровати)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast", "has_internet"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "110.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Standard",
            "main_name": "Двухместный номер Standard",
            "bathroom": null,
            "bedding_type": "2 отдельные кровати",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
      ],
      "hotel": {
        "id": "maajid_hotel",
        "kind": "Hotel",
        "name": "Maajid Hotel & Restaurant",
        "email": "reservation@maajidhotel.com",
        "facts": {
          "year_built": null,
          "electricity": {
            "sockets": ["c", "f"],
            "voltage": [220],
            "frequency": [50],
          },
          "rooms_number": 15,
          "floors_number": null,
          "year_renovated": null,
        },
        "phone": "+994124922101",
        "images": [
          "https://cdn.worldota.net/t/{size}/extranet/d2/e4/d2e448c6dc89f25c3f231936ad4065730ff5913e.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/fd/2e/fd2e48628a5a4dbe43a3cf8d539423d25daadce2.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/27/70/27701363a572d7691c1721b8544500af9ca0cd23.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/7d/eb/7deb9de2bb06e68793d55d04e8dee9833c0e6c50.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/0f/78/0f78dd53e8f9d8e1eee8419926c229ac258d2c48.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/9b/a5/9ba56a96ab9985f3c7d869d00ae78a3c6639b5f2.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/41/00/4100a773641bfe1bfc391861180df3e55d6c4874.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/f5/f0/f5f03cc91c36c8e0a319f863c1db3cbfb18404de.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/7a/e2/7ae27158a3dfab0196c1ce73ebee01e9b157fe25.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/0c/b5/0cb5e2635ad163c091216450839a14497c5fcac3.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/74/90/749060f256ab49bcf6b57110932fae20cf3e4b48.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/70/ab/70ab4dbd3aed18e958a5ba8a3eafa5f4ee476919.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/25/31/25313b67221557f2afe835eca6806222137b5bb5.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/1f/5a/1f5ad4df740ac9af20f0ca821d17f573e423660a.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/c6/ac/c6ac2e863412002139e66d525622d6866353eb11.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/5f/8c/5f8ce8cad0d15bbce92529edb3859fc1c9af2cb5.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/15/07/15075a49bbb3c077b82ed639da48ecb37b3f5b18.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/bf/52/bf52f770cbd72243205a6f3bc9298842d91741e0.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/0a/a9/0aa9805e9d96c540d6a36e47aa174bfec601b9c8.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/94/53/945335ad73659c91bcbbde424fe9ddebe744f978.jpeg",
        ],
        "region": {
          "id": 492,
          "iata": "BAK",
          "name": "Баку",
          "type": "City",
          "country_code": "AZ",
        },
        "address": "58, 1st Gasr, Old City, Баку",
        "latitude": 40.36565017700195,
        "is_closed": false,
        "longitude": 49.83281326293945,
        "hotel_chain": "No chain",
        "postal_code": "1000",
        "room_groups": [
          {
            "name": "Двухместный номер Economy двуспальная кровать",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/ef/ef/efef799da4cb721c0934d2423b3e8e8bce8d8868.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/10/8a/108a44e749a8e575a6d89e188bc7765aed3198d7.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/c6/62/c662aded7917ae85e7c93fea0b749733d3f52027.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 3,
              "quality": 1,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 2,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Двухместный номер Economy",
              "bedding_type": "двуспальная кровать",
            },
            "room_group_id": 71,
            "room_amenities": [
              "air-conditioning",
              "bedsheets",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "hypoallergenic",
              "mini-bar",
              "mirror",
              "mosquito",
              "private-bathroom",
              "private-entrance",
              "safe",
              "shower",
              "telephone",
              "toiletries",
              "tv",
            ],
          },
          {
            "name": "Одноместный номер Standard односпальная кровать",
            "images": [
              "https://cdn.worldota.net/t/{size}/content/a1/6a/a16a948cdff201f01e6cb08f01295d6d47611905.jpeg",
              "https://cdn.worldota.net/t/{size}/content/55/32/55326357ee6af5f44a18eb1991de0b1bb3d9bb0e.jpeg",
              "https://cdn.worldota.net/t/{size}/content/ab/f8/abf8a181d792d4c7ed32a26552e022574b3b96f0.jpeg",
              "https://cdn.worldota.net/t/{size}/content/f2/68/f26865195a40e63d41ab39805a7bc159ba14ed1a.jpeg",
              "https://cdn.worldota.net/t/{size}/content/36/52/36523454a1ac0fd9340de153d577be087ae34614.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 2,
              "quality": 2,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 1,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Одноместный номер Standard",
              "bedding_type": "односпальная кровать",
            },
            "room_group_id": 19509812,
            "room_amenities": ["private-bathroom"],
          },
          {
            "name":
                "Двухместный номер Standard с видом на город двуспальная кровать",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/08/4e/084e232a4496dabc86db0cb1b729326c4d8455f3.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/61/ec/61ec83e7382d4ed3ce4d48ddba76d902e6da66c4.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/ef/ef/efef799da4cb721c0934d2423b3e8e8bce8d8868.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/d9/b2/d9b239e7ecfaec439f6dd4f92bc3f570d4695d8e.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 5,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 3,
              "quality": 2,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 2,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Двухместный номер Standard с видом на город",
              "bedding_type": "двуспальная кровать",
            },
            "room_group_id": 20591156,
            "room_amenities": [
              "air-conditioning",
              "bedsheets",
              "blackout-blinds",
              "desk",
              "fireplace",
              "fridge",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "mosquito",
              "private-bathroom",
              "private-entrance",
              "safe",
              "shower",
              "slippers",
              "tea",
              "tea-or-coffee",
              "telephone",
              "toiletries",
              "tv",
              "wardrobe",
              "water",
              "with-view",
            ],
          },
          {
            "name": "Двухместный номер Standard 2 отдельные кровати",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/80/32/8032add86afd890771a3659988a4b41c20eab85c.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/7f/f9/7ff9c202f0a3c5cde96076ef697e4f94d086b1f2.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/29/3c/293c04c713fbf8ec2da3e6bad33190b4d1521b0f.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 4,
              "quality": 2,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 2,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Двухместный номер Standard",
              "bedding_type": "2 отдельные кровати",
            },
            "room_group_id": 91,
            "room_amenities": [
              "air-conditioning",
              "bedsheets",
              "blackout-blinds",
              "desk",
              "fireplace",
              "fridge",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "mosquito",
              "private-bathroom",
              "private-entrance",
              "safe",
              "shower",
              "slippers",
              "tea",
              "tea-or-coffee",
              "telephone",
              "toiletries",
              "tv",
              "wardrobe",
              "water",
            ],
          },
          {
            "name": "Трёхместный номер Deluxe",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/8f/75/8f75731e4a8c287a58a38e2a4478641a9c3e8d0d.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/75/19/751901e0970b70f8b9606bf6977b020c5ed65dd7.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/c8/85/c8858da649b50c44df4ce804b2c567406ed22ac2.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 0,
              "quality": 6,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 3,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Трёхместный номер Deluxe",
              "bedding_type": null,
            },
            "room_group_id": 21541492,
            "room_amenities": [
              "air-conditioning",
              "bedsheets",
              "blackout-blinds",
              "desk",
              "fireplace",
              "fridge",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "mosquito",
              "private-bathroom",
              "private-entrance",
              "safe",
              "shower",
              "slippers",
              "tea",
              "tea-or-coffee",
              "telephone",
              "toiletries",
              "tv",
              "wardrobe",
              "water",
            ],
          },
          {
            "name":
                "Двухместный номер Deluxe с видом на город двуспальная кровать",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/f1/e9/f1e987a8b99d44b5e023d5d7c5bb9492097dc064.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/97/db/97dbf8d8853181c2a22a084413fcc63fc5b8ade7.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/e5/31/e531b2d911d04fc0dadbff5217494b11f9a67b6d.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/c1/10/c11038533c7cc0a0d4caf68e6085d0db61597f5a.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/c8/85/c8858da649b50c44df4ce804b2c567406ed22ac2.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 5,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 3,
              "quality": 6,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 2,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Двухместный номер Deluxe с видом на город",
              "bedding_type": "двуспальная кровать",
            },
            "room_group_id": 20591220,
            "room_amenities": [
              "air-conditioning",
              "bedsheets",
              "blackout-blinds",
              "desk",
              "fireplace",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "hypoallergenic",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "mosquito",
              "private-bathroom",
              "private-entrance",
              "safe",
              "shower",
              "slippers",
              "tea",
              "tea-or-coffee",
              "telephone",
              "toiletries",
              "tv",
              "wardrobe",
              "water",
              "with-view",
            ],
          },
          {
            "name":
                "Двухместный люкс с балконом и с красивым видом из окна двуспальная кровать",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/d6/dd/d6dd36519f72fee3324913ba77ded9194a95852c.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/ac/3f/ac3f46bfc329976242636aa716bf8ae3813b20b1.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/7e/d1/7ed1d5d17bc03ac78ec534b529d05adea96e0fb7.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/b3/ab/b3abc235e4f1e21a910a37ec19bd1bb44711ec68.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/71/76/717694add538b5af6493cc5f85072bd09ea4739c.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/dd/18/dd1883baa00f76449611c9e4e6894dd7bdf1adc3.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/0a/87/0a8798e023771bfe23b06f7478140cdafefff750.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/6b/f8/6bf83998793b407c6b5bc01289104e54b13e4e77.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 37,
              "class": 5,
              "floor": 0,
              "family": 0,
              "balcony": 1,
              "bedding": 3,
              "quality": 0,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 2,
            },
            "name_struct": {
              "bathroom": null,
              "main_name":
                  "Двухместный люкс с балконом и с красивым видом из окна",
              "bedding_type": "двуспальная кровать",
            },
            "room_group_id": 20591126,
            "room_amenities": [
              "air-conditioning",
              "balcony",
              "bath",
              "bathrobe",
              "bedsheets",
              "desk",
              "dining-area",
              "fireplace",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "hypoallergenic",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "private-bathroom",
              "private-entrance",
              "safe",
              "shower",
              "slippers",
              "soundproofing",
              "tea",
              "tea-or-coffee",
              "telephone",
              "toiletries",
              "towels",
              "tv",
              "wardrobe",
              "water",
              "with-view",
            ],
          },
        ],
        "star_rating": 4,
        "serp_filters": [
          "has_internet",
          "has_airport_transfer",
          "has_parking",
          "has_kids",
          "has_meal",
          "has_business",
          "air_conditioning",
          "has_smoking",
        ],
        "check_in_time": "14:00:00",
        "policy_struct": [
          {
            "title": "Питание",
            "paragraphs": [
              "Информация о типе питания, включенном в стоимость, указана в деталях тарифа.",
              "Питание может быть ограничено в период Рамадана.",
            ],
          },
          {
            "title":
                "Размещение с детьми и информация о дополнительных кроватях",
            "paragraphs": [
              "Плата за дополнительную кровать: 20.00 AZN за ночь.",
              "Количество дополнительных кроватей зависит от категории номера. Необходимо ознакомиться с информацией о вместимости выбранного номера.",
            ],
          },
          {
            "title": "Особые условия проживания",
            "paragraphs": [
              "Необходимо внести депозит. Стоимость: 100.00 AZN за номер.",
              "Если для въезда в страну вам требуется виза, ваш отель в большинстве случаев предоставит вам необходимые документы для ее получения. За более подробной информацией обращайтесь в отель, контактная информация указана в подтверждении бронирования. За эти услуги может взиматься дополнительная плата, даже в случае последующей отмены бронирования. Все договоренности осуществляются исключительно между вами и отелем.",
              "Пары, въезжающие в один номер должны предоставить свидетельство о браке при регистрации заезда. В противном случае, объект может отклонить бронирование или запросить бронирование второго номера.",
            ],
          },
          {
            "title": "Парковка",
            "paragraphs": [
              "Chargeable public parking available in the nearby area. Cost: 25.00 AZN per day.",
            ],
          },
          {
            "title": "Трансфер",
            "paragraphs": [
              "Предоставляется трансфер от/до аэропорта. Стоимость: 35.00 AZN в одну сторону.",
            ],
          },
          {
            "title": "Дополнительно",
            "paragraphs": [
              "Гостям отеля необходимо предоставить справку о прививке от Covid-19, ее запрашивают при въезде в страну.",
            ],
          },
        ],
        "amenity_groups": [
          {
            "amenities": [
              "Кондиционер",
              "Круглосуточная стойка регистрации",
              "Лифт",
              "Места для курения",
              "Обмен валюты",
              "Отель для некурящих",
              "Отопление",
              "Пресса",
              "Телевизор в лобби",
              "Терраса",
              "Ускоренная регистрация заезда",
              "Ранняя регистрация заезда",
              "Поздняя регистрация выезда",
              "Дизайн-отель",
              "Дворецкий",
              "Огнетушитель",
              "Мебель на улице",
              "Работают лифты для доступа к верхним этажам",
            ],
            "group_name": "Общее",
          },
          {
            "amenities": [
              "Люкс для новобрачных",
              "Номера для аллергиков",
              "Номера для некурящих",
              "Холодильник",
              "Семейные номера",
              "VIP-удобства в номере",
              "Кабельное телевидение",
              "Телевизор",
              "Мини-бар",
              "Халат",
              "Москитная сетка",
              "Сейф (в номере)",
            ],
            "group_name": "В номерах",
          },
          {
            "amenities": [
              "Гладильные принадлежности",
              "Гладильные услуги",
              "Прачечная",
              "Услуги консьержа",
              "Фен (по запросу)",
              "Хранение багажа",
              "Телефон",
              "Утюг",
            ],
            "group_name": "Услуги и удобства",
          },
          {
            "amenities": [
              "Бар",
              "Бесплатный чай/кофе",
              "Завтрак",
              "Кафе",
              "Ресторан",
            ],
            "group_name": "Питание",
          },
          {
            "amenities": ["Бесплатный Wi-Fi", "Бесплатный доступ в интернет"],
            "group_name": "Интернет",
          },
          {
            "amenities": ["Прокат автомобилей", "Трансфер от аэропорта"],
            "group_name": "Трансфер",
          },
          {
            "amenities": ["на русском", "на английском"],
            "group_name": "Персонал говорит",
          },
          {
            "amenities": ["Экскурсионное бюро"],
            "group_name": "Туризм",
          },
          {
            "amenities": ["Развлекательные мероприятия"],
            "group_name": "Развлечения",
          },
          {
            "amenities": ["Парковка рядом с отелем"],
            "group_name": "Парковка",
          },
          {
            "amenities": ["Ксерокс", "Конференц-зал"],
            "group_name": "Бизнес",
          },
          {
            "amenities": [
              "Игровая комната",
              "Размещение подходит для семей/детей",
              "Детские телеканалы",
            ],
            "group_name": "Дети",
          },
          {
            "amenities": ["Размещение с домашними животными не допускается"],
            "group_name": "Животные",
          },
        ],
        "check_out_time": "12:00:00",
        "payment_methods": [
          "visa",
          "maestro",
          "china_unionpay",
          "euro_master_card",
          "cash",
        ],
        "semantic_version": 0,
        "star_certificate": null,
        "metapolicy_struct": {
          "cot": [
            {
              "price": "0.00",
              "amount": 1,
              "currency": "AZN",
              "inclusion": "not_included",
              "price_unit": "per_room_per_night",
            },
          ],
          "meal": [],
          "pets": [],
          "visa": {"visa_support": "support_enable"},
          "add_fee": [],
          "deposit": [
            {
              "price": "100.00",
              "currency": "AZN",
              "price_unit": "per_room_per_stay",
              "availability": "available",
              "deposit_type": "unspecified",
              "payment_type": "unspecified",
              "pricing_method": "fixed",
            },
          ],
          "no_show": {
            "time": null,
            "day_period": "unspecified",
            "availability": "unspecified",
          },
          "parking": [
            {
              "price": "25.00",
              "currency": "AZN",
              "inclusion": "not_included",
              "price_unit": "per_guest_per_night",
              "territory_type": "off_side",
            },
          ],
          "shuttle": [
            {
              "price": "35.00",
              "currency": "AZN",
              "inclusion": "not_included",
              "shuttle_type": "one_way",
              "destination_type": "airport",
            },
          ],
          "children": [
            {
              "price": "0.00",
              "age_end": 3,
              "currency": null,
              "age_start": 0,
              "extra_bed": "available",
            },
          ],
          "internet": [],
          "extra_bed": [
            {
              "price": "20.00",
              "amount": 1,
              "currency": "AZN",
              "inclusion": "not_included",
              "price_unit": "per_guest_per_night",
            },
          ],
          "children_meal": [],
          "check_in_check_out": [],
        },
        "description_struct": [
          {
            "title": "Расположение",
            "paragraphs": [
              "Отдых должен быть комфортным! Отель «Maajid Hotel &amp; Restaurant» находится в Баку. Этот отель расположен в пешей доступности от центра города. Рядом с отелем можно прогуляться. Неподалёку: Дворец Ширваншахов, Старый город Баку и Девичья башня.",
            ],
          },
          {
            "title": "В отеле",
            "paragraphs": [
              "Скоротать вечер или приятно провести время перед сном в уютной атмосфере можно в баре. Время вспомнить о хлебе насущном! Для гостей работает ресторан. Попробуйте кофе в кафе — вдруг именно он станет лучшим в городе? На территории работает бесплатный Wi-Fi. Уточняйте информацию сразу при заезде.",
              "Если вы путешествуете на машине, припарковаться можно будет на платной парковке. Скучно не будет, ведь в отеле к услугам отдыхающих развлекательные мероприятия. В отеле есть игровые детские комнаты. Будьте готовы к тому, что детям будет весело, а вам придется коротать вечер со взрослыми. Если планируете экскурсии, обратите внимание на экскурсионное бюро отеля.",
              "Чтобы путешествие было не только приятным, но и удобным, гости могут заказать трансфер. Удобно для гостей с ограниченными возможностями: на верхние этажи гостей поднимает лифт. Гостям доступны и другие услуги. Например, прачечная, гладильные услуги, пресса, прокат автомобилей и консьерж. Персонал отеля говорит на английском и русском.",
            ],
          },
          {
            "title": "В номере",
            "paragraphs": [
              "Номер уютно обставлен и оснащён необходимым, чтобы отдохнуть после долгого и насыщенного дня. Имеются телевизор, мини-бар и халат. Оснащение зависит от выбранной категории номера.",
            ],
          },
        ],
        "front_desk_time_end": "00:00:00",
        "front_desk_time_start": "00:00:00",
        "metapolicy_extra_info":
            "Гостям отеля необходимо предоставить справку о прививке от Covid-19, ее запрашивают при въезде в страну.",
        "is_gender_specification_required": false,
      },
    },
    {
      "id": "moss_art_hotel",
      "hid": 10214846,
      "rates": [
        {
          "match_hash": "m-922cb299-a3f3-5f2d-85ae-d8b9a9a53c6d",
          "search_hash": null,
          "daily_prices": ["3818.67", "3818.67", "3818.67"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "11456.00",
                "show_amount": "11456.00",
                "currency_code": "RUB",
                "show_currency_code": "RUB",
                "by": "credit_card",
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "now",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "6.78",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "1747.53",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": null,
                      "amount_charge": "11456.00",
                      "amount_show": "11456.00",
                    },
                  ],
                  "free_cancellation_before": null,
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 2,
            "sex": 0,
            "bathroom": 2,
            "bedding": 4,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Standard (2 отдельные кровати)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "225.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Standard",
            "main_name": "Двухместный номер Standard",
            "bathroom": null,
            "bedding_type": "2 отдельные кровати",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-388b54cb-9218-5054-9be2-f3135e303eaf",
          "search_hash": null,
          "daily_prices": ["4837.00", "4837.00", "4837.00"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "14511.00",
                "show_amount": "14511.00",
                "currency_code": "RUB",
                "show_currency_code": "RUB",
                "by": "credit_card",
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "now",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "6.78",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2213.54",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": "2025-03-25T10:00:00",
                      "amount_charge": "0.00",
                      "amount_show": "0.00",
                    },
                    {
                      "start_at": "2025-03-25T10:00:00",
                      "end_at": null,
                      "amount_charge": "14511.00",
                      "amount_show": "14511.00",
                    },
                  ],
                  "free_cancellation_before": "2025-03-25T10:00:00",
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 2,
            "sex": 0,
            "bathroom": 2,
            "bedding": 4,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name": "Двухместный номер Standard (2 отдельные кровати)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast"],
          "allotment": 1,
          "amenities_data": ["non-smoking"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "95.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Standard",
            "main_name": "Двухместный номер Standard",
            "bathroom": null,
            "bedding_type": "2 отдельные кровати",
            "misc_room_type": null,
          },
          "legal_info": null,
        },
        {
          "match_hash": "m-9ba26d84-a329-58f4-b601-6d072531dc33",
          "search_hash": null,
          "daily_prices": ["6110.00", "6110.00", "6110.00"],
          "meal": "breakfast",
          "meal_data": {
            "value": "breakfast",
            "has_breakfast": true,
            "no_child_meal": false,
          },
          "payment_options": {
            "payment_types": [
              {
                "amount": "18330.00",
                "show_amount": "18330.00",
                "currency_code": "RUB",
                "show_currency_code": "RUB",
                "by": "credit_card",
                "is_need_credit_card_data": true,
                "is_need_cvc": true,
                "type": "now",
                "tax_data": {
                  "taxes": [
                    {
                      "name": "city_tax",
                      "included_by_supplier": false,
                      "amount": "6.78",
                      "currency_code": "AZN",
                    },
                    {
                      "name": "vat",
                      "included_by_supplier": true,
                      "amount": "2796.10",
                      "currency_code": "RUB",
                    },
                  ],
                },
                "cancellation_penalties": {
                  "policies": [
                    {
                      "start_at": null,
                      "end_at": null,
                      "amount_charge": "18330.00",
                      "amount_show": "18330.00",
                    },
                  ],
                  "free_cancellation_before": null,
                },
              },
            ],
          },
          "rg_ext": {
            "class": 3,
            "quality": 5,
            "sex": 0,
            "bathroom": 2,
            "bedding": 4,
            "family": 0,
            "capacity": 2,
            "club": 0,
            "bedrooms": 0,
            "balcony": 0,
            "view": 0,
            "floor": 0,
          },
          "room_name":
              "Двухместный номер Superior (2 отдельные кровати) (+ диван)",
          "room_name_info": null,
          "serp_filters": ["has_bathroom", "has_breakfast"],
          "allotment": 1,
          "amenities_data": ["non-smoking", "sofa"],
          "any_residency": true,
          "deposit": null,
          "no_show": {
            "amount": "360.00",
            "currency_code": "AZN",
            "from_time": "12:00:00",
          },
          "room_data_trans": {
            "main_room_type": "Двухместный номер Superior",
            "main_name": "Двухместный номер Superior",
            "bathroom": null,
            "bedding_type": "2 отдельные кровати",
            "misc_room_type": "+ диван",
          },
          "legal_info": null,
        },
      ],
      "hotel": {
        "id": "moss_art_hotel",
        "kind": "Hotel",
        "name": "Отель Moss Art",
        "email": "mossartboutique@gmail.com",
        "facts": {
          "year_built": null,
          "electricity": {
            "sockets": ["c", "f"],
            "voltage": [220],
            "frequency": [50],
          },
          "rooms_number": 15,
          "floors_number": null,
          "year_renovated": null,
        },
        "phone": "+994 70 595 03 45",
        "images": [
          "https://cdn.worldota.net/t/{size}/extranet/52/72/5272048cdbda5f1db9dd240a693b6a33340e93ef.JPEG",
          "https://cdn.worldota.net/t/{size}/extranet/d4/6e/d46efb63e5082d6dbd8e4e7ffd25320ad426aaea.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/6d/cf/6dcf9ee4a2299bd0b95d6389fdb7b57f543fec45.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/09/72/0972495c96aa4d35fe12eb13b34b1bbe03c4524b.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/f0/1f/f01f06f80b6003d98c53028e575c82d875be4752.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/80/36/803616fe0f37e233a79a514916850cbd28e79218.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/88/af/88af63f35ef9fbe00a070f5cd2239be3eeec4534.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/25/cc/25cc96b081dab8935b7b302828b9c8a3845a3a9d.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/48/4f/484febcb781e787160983d616fd59814ba233091.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/7e/25/7e25743b7a914eeab63b3292085b891cb4182d5a.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/9e/34/9e3466acfe180d5243dd49851ff2cba1c16ee934.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/eb/d2/ebd27f16b23efbd5ceab9363a88ef157869809ac.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/ba/34/ba348de192680943dcd2222afb5e997b3219c169.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/7b/37/7b37fa0f02899efc8d34ae5bdebb451d9c71a867.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/f2/fc/f2fc420848cdf3211a848f2a0150238132c969f2.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/de/e8/dee8130e1837f5c05314afe0d36d1d61def712f0.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/33/c9/33c93e6010c35bfe236c8ffb1a30f247b0c9eb35.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/b2/70/b270588dd860c2afbedef11f3f4f010b78721741.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/d7/fb/d7fb5596138f6311bb8af721b9ec04ff56bdff04.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/99/21/9921f6307efe961e26faf0d6aa14986bd8a427fb.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/58/a2/58a283fcebfbc92ee5a6012585c8f9129317f462.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/81/49/8149368f953d91e1236a9ca8e32737e2b17a2dfe.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/20/4d/204d82e6ac900481391a638d6addeb8db8e44c0c.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/12/df/12df0baa5dac18a8f3990eb73d5325544477af75.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/a2/60/a2604abc7fc47828dbf7402d8064461bb9433719.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/cb/b0/cbb009c70b11037b0b614e03578280041987f5cf.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/36/a1/36a1b0d725eae1cdc6b21b21902fdb3e3a8d69bd.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/53/45/534501ef97ab53669027c09aad29a5d561767a77.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/f2/db/f2dbf1e11959407089e151b82fedb3cc428f3ee1.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/88/fd/88fd0ec98117fa19bd36c4b076adcd91f03912b2.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/e8/c3/e8c39bb6c096e4f9c201ac0a83f2f62cfaaca189.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/c1/ee/c1ee9dca284ed05a81136c27bb7065d479e71d3e.jpeg",
          "https://cdn.worldota.net/t/{size}/extranet/0e/b9/0eb9a276bb483bc0d82bf80c72a7a511c5862637.JPEG",
          "https://cdn.worldota.net/t/{size}/extranet/48/0b/480bdf35a0380d386ec41404746583ee798294be.JPEG",
          "https://cdn.worldota.net/t/{size}/extranet/c0/7c/c07c2cfc2c07a16a72f27ed1cbf098b4f61fb18f.JPEG",
          "https://cdn.worldota.net/t/{size}/extranet/fb/16/fb1656cf3633693ba0f34042c7594ad2213d55df.JPEG",
        ],
        "region": {
          "id": 492,
          "iata": "BAK",
          "name": "Баку",
          "type": "City",
          "country_code": "AZ",
        },
        "address": "улица Ислама Сафарли, д.15, Баку",
        "latitude": 40.3726806640625,
        "is_closed": false,
        "longitude": 49.834903717041016,
        "hotel_chain": "No chain",
        "postal_code": "1005",
        "room_groups": [
          {
            "name": "Одноместный номер Standard с балконом",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/dc/6b/dc6b6014a6a52c5c634c15a07cbce2d087810544.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/b2/f8/b2f8bb41dfa5145e6f7cea8bbaed87bd285df24f.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/3d/9c/3d9c8d2af317ef9bc63f25e3d460066d895d0a81.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/b4/f4/b4f4688dbfaf285882fdf8b686f2882374baf071.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/43/fd/43fd1bcf55a8ec4431c021efc65ca6adf3f7055d.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/88/af/88af63f35ef9fbe00a070f5cd2239be3eeec4534.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/03/c3/03c393766620d88893f07d55bf367e40a72d766a.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/25/cc/25cc96b081dab8935b7b302828b9c8a3845a3a9d.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/d7/ea/d7eac141bee1d291f9fbc8b549051eb16aa04d4f.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 1,
              "bedding": 0,
              "quality": 2,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 1,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Одноместный номер Standard с балконом",
              "bedding_type": null,
            },
            "room_group_id": 19444276,
            "room_amenities": [
              "addon-service",
              "air-conditioning",
              "balcony",
              "bedsheets",
              "blackout-blinds",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "hypoallergenic",
              "iron",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "mosquito",
              "patio",
              "private-bathroom",
              "shower",
              "slippers",
              "soundproofing",
              "tea",
              "tea-or-coffee",
              "telephone",
              "toiletries",
              "tv",
              "wardrobe",
              "water",
            ],
          },
          {
            "name": "Двухместный номер Standard двуспальная кровать",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/4d/1c/4d1c265429f5447d7e3418b5c38cab971a94cb5d.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/37/7f/377ff6e28ede3694b925c339215c56a39e464b79.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/48/4f/484febcb781e787160983d616fd59814ba233091.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/88/af/88af63f35ef9fbe00a070f5cd2239be3eeec4534.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/21/72/2172cdf29a1d3c9f440220bd13088df6b4894697.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/6c/cf/6ccf5e3b1bf5f8ba86342ea84070ffc3861fc11f.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/8a/f6/8af6e4f343f3f4a713a6248fef319e12370743c3.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/a6/d2/a6d2d67b10e8a68aa0bd50c6bb40c09c4f13ce04.JPEG",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 3,
              "quality": 2,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 2,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Двухместный номер Standard",
              "bedding_type": "двуспальная кровать",
            },
            "room_group_id": 90,
            "room_amenities": [
              "addon-service",
              "air-conditioning",
              "blackout-blinds",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "hypoallergenic",
              "iron",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "mosquito",
              "private-bathroom",
              "shower",
              "slippers",
              "tea",
              "tea-or-coffee",
              "tv",
              "wardrobe",
              "water",
            ],
          },
          {
            "name": "Двухместный номер Standard 2 отдельные кровати",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/80/36/803616fe0f37e233a79a514916850cbd28e79218.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/d4/cd/d4cd19d50b5775c1d91a16b9ce6de79bb2378058.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/cf/f5/cff590bf0eff086ab122ba1d5610262d216df8d7.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/b2/c4/b2c45ce8cc00bcc6e890ef1ef71ad48a2d6e698c.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/25/cc/25cc96b081dab8935b7b302828b9c8a3845a3a9d.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/37/7f/377ff6e28ede3694b925c339215c56a39e464b79.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/37/f8/37f89ba5ebf71becc2f283a5963d800d13566e6e.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/f2/04/f204ca6667ae871afce6a08bd470e24f6300745e.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/6f/a3/6fa30d3f6b3b70dc974b614e2f24aa88a4d7153e.JPEG",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 4,
              "quality": 2,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 2,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Двухместный номер Standard",
              "bedding_type": "2 отдельные кровати",
            },
            "room_group_id": 91,
            "room_amenities": [
              "addon-service",
              "air-conditioning",
              "bathrobe",
              "blackout-blinds",
              "desk",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "hypoallergenic",
              "iron",
              "kitchen-stuff",
              "mirror",
              "mosquito",
              "private-bathroom",
              "safe",
              "shower",
              "slippers",
              "soundproofing",
              "tea",
              "tea-or-coffee",
              "toiletries",
              "tv",
              "wardrobe",
              "water",
            ],
          },
          {
            "name": "Трёхместный номер Superior",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/af/97/af97740b56806d5bb4b5086dc2eabe4d8884449e.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/32/3e/323e4372aff27b4a569d1731dff350c6da6c46c5.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/18/af/18aff006602e2769e260c0d3ddcf52dfe51b5c3c.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 0,
              "quality": 5,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 3,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Трёхместный номер Superior",
              "bedding_type": null,
            },
            "room_group_id": 21541476,
            "room_amenities": [
              "addon-service",
              "air-conditioning",
              "blackout-blinds",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "hypoallergenic",
              "iron",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "mosquito",
              "patio",
              "private-bathroom",
              "shower",
              "slippers",
              "soundproofing",
              "tea",
              "tea-or-coffee",
              "telephone",
              "toiletries",
              "tv",
              "wardrobe",
              "water",
            ],
          },
          {
            "name": "Двухместный номер Superior 2 отдельные кровати",
            "images": [
              "https://cdn.worldota.net/t/{size}/extranet/40/db/40dbf98d9a6ef80579fa9206e40364efe12c2ec5.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/97/17/971722c9874d92d1bd1152950d70438f914187b2.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/d7/31/d731e12e8e8981065e10b87128616e6a6a53a583.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/ff/2b/ff2b463a79eb22ffffb92c4a6120e22ce90f6df1.JPEG",
              "https://cdn.worldota.net/t/{size}/extranet/7b/37/7b37fa0f02899efc8d34ae5bdebb451d9c71a867.jpeg",
              "https://cdn.worldota.net/t/{size}/extranet/75/65/756538ab99be2797c553edad2fc2a225054b4e3c.jpeg",
            ],
            "rg_ext": {
              "sex": 0,
              "club": 0,
              "view": 0,
              "class": 3,
              "floor": 0,
              "family": 0,
              "balcony": 0,
              "bedding": 4,
              "quality": 5,
              "bathroom": 2,
              "bedrooms": 0,
              "capacity": 2,
            },
            "name_struct": {
              "bathroom": null,
              "main_name": "Двухместный номер Superior",
              "bedding_type": "2 отдельные кровати",
            },
            "room_group_id": 124,
            "room_amenities": [
              "addon-service",
              "air-conditioning",
              "bathrobe",
              "bedsheets",
              "blackout-blinds",
              "hairdryer",
              "heating",
              "high-speed-internet-access",
              "hypoallergenic",
              "iron",
              "kitchen-stuff",
              "mini-bar",
              "mirror",
              "mosquito",
              "private-bathroom",
              "shower",
              "slippers",
              "soundproofing",
              "tea",
              "tea-or-coffee",
              "telephone",
              "toiletries",
              "tv",
              "wardrobe",
              "water",
            ],
          },
        ],
        "star_rating": 3,
        "serp_filters": [
          "has_internet",
          "has_airport_transfer",
          "has_parking",
          "has_kids",
          "air_conditioning",
          "has_smoking",
        ],
        "check_in_time": "14:00:00",
        "policy_struct": [
          {
            "title": "Питание",
            "paragraphs": [
              "Информация о типе питания, включенном в стоимость, указана в деталях тарифа.",
              "Питание может быть ограничено в период Рамадана.",
            ],
          },
          {
            "title": "Особые условия проживания",
            "paragraphs": [
              "Если для въезда в страну вам требуется виза, ваш отель в большинстве случаев предоставит вам необходимые документы для ее получения. За более подробной информацией обращайтесь в отель, контактная информация указана в подтверждении бронирования. За эти услуги может взиматься дополнительная плата, даже в случае последующей отмены бронирования. Все договоренности осуществляются исключительно между вами и отелем.",
              "Пары, въезжающие в один номер должны предоставить свидетельство о браке при регистрации заезда. В противном случае, объект может отклонить бронирование или запросить бронирование второго номера.",
            ],
          },
          {
            "title": "Трансфер",
            "paragraphs": [
              "Предоставляется трансфер от/до аэропорта. Стоимость: 25.00 EUR в одну сторону.",
            ],
          },
          {
            "title": "Дополнительно",
            "paragraphs": [
              "<p>You'll be asked to pay the following charges at the property:</p> <ul><li>A tax is imposed by the city: EUR 0.61 per person, per night</li><li>Shuttle transfer per adult: EUR 25 (one-way)</li><li>Shuttle transfer per child: EUR 0 (one-way)</li> </ul> <p>We have included all charges provided to us by the property. </p><br /><br /><br /><ul>      <li>Airport shuttle fee: EUR 25 per vehicle (maximum occupancy 5)</li> <li>Airport shuttle fee per child: EUR 0 (up to 10 years old)</li>  <li>Self parking fee: EUR 5 per day</li>                       </ul> <p>The above list may not be comprehensive. Fees and deposits may not include tax and are subject to change. </p>",
            ],
          },
        ],
        "amenity_groups": [
          {
            "amenities": [
              "Магазины",
              "Кондиционер",
              "Круглосуточная стойка регистрации",
              "Обмен валюты",
              "Отель для некурящих",
              "Отопление",
              "Продажа билетов",
              "Телевизор в лобби",
              "Ускоренная регистрация выезда",
              "Ранняя регистрация заезда",
              "Поздняя регистрация выезда",
              "Аптека",
              "Индивидуальная регистрация заезда и отъезда",
              "Огнетушитель",
              "Отсутствие лифтов",
            ],
            "group_name": "Общее",
          },
          {
            "amenities": [
              "Номера для аллергиков",
              "Номера для некурящих",
              "Обслуживание номеров",
              "Холодильник",
              "Номера для курящих",
              "Семейные номера",
              "Кабельное телевидение",
              "Телевизор",
              "Мини-бар",
              "Москитная сетка",
              "Сейф (в номере)",
            ],
            "group_name": "В номерах",
          },
          {
            "amenities": [
              "Гладильные услуги",
              "Прачечная",
              "Услуги консьержа",
              "Химчистка",
              "Фен (по запросу)",
              "Хранение багажа",
              "Телефон",
              "Утюг",
            ],
            "group_name": "Услуги и удобства",
          },
          {
            "amenities": [
              "Бесплатный чай/кофе",
              "Завтрак",
              "Завтрак в номер",
              "Микроволновая печь",
            ],
            "group_name": "Питание",
          },
          {
            "amenities": ["Бесплатный Wi-Fi", "Бесплатный доступ в интернет"],
            "group_name": "Интернет",
          },
          {
            "amenities": [
              "Трансфер",
              "Прокат автомобилей",
              "Трансфер от аэропорта",
            ],
            "group_name": "Трансфер",
          },
          {
            "amenities": ["на русском", "на английском"],
            "group_name": "Персонал говорит",
          },
          {
            "amenities": ["Экскурсионное бюро"],
            "group_name": "Туризм",
          },
          {
            "amenities": ["Прокат велосипедов"],
            "group_name": "Развлечения",
          },
          {
            "amenities": ["Парковка (по запросу)", "Парковка рядом с отелем"],
            "group_name": "Парковка",
          },
          {
            "amenities": ["Ксерокс"],
            "group_name": "Бизнес",
          },
          {
            "amenities": ["Аптечка первой помощи"],
            "group_name": "Красота и здоровье",
          },
          {
            "amenities": [
              "Размещение подходит для семей/детей",
              "Детские телеканалы",
            ],
            "group_name": "Дети",
          },
          {
            "amenities": ["Размещение с домашними животными не допускается"],
            "group_name": "Животные",
          },
          {
            "amenities": [
              "Усиленные меры дезинфекции",
              "Температурный контроль для гостей",
            ],
            "group_name": "Санитарные меры",
          },
        ],
        "check_out_time": "12:00:00",
        "payment_methods": ["visa", "maestro", "euro_master_card", "cash"],
        "semantic_version": 0,
        "star_certificate": null,
        "metapolicy_struct": {
          "cot": [
            {
              "price": "0.00",
              "amount": 1,
              "currency": "AZN",
              "inclusion": "not_included",
              "price_unit": "per_room_per_night",
            },
          ],
          "meal": [],
          "pets": [],
          "visa": {"visa_support": "support_enable"},
          "add_fee": [],
          "deposit": [],
          "no_show": {
            "time": null,
            "day_period": "unspecified",
            "availability": "unspecified",
          },
          "parking": [],
          "shuttle": [
            {
              "price": "25.00",
              "currency": "EUR",
              "inclusion": "not_included",
              "shuttle_type": "one_way",
              "destination_type": "airport",
            },
          ],
          "children": [],
          "internet": [],
          "extra_bed": [],
          "children_meal": [],
          "check_in_check_out": [],
        },
        "description_struct": [
          {
            "title": "Расположение",
            "paragraphs": [
              "Отель, где хорошо отдыхать перед долгими прогулками. Отель «Отель Moss Art» расположен в Баку. Этот отель находится в центре города. Перед сном есть возможность прогуляться вдоль главных достопримечательностей. Рядом с отелем — Площадь фонтанов, Музей Низами Гянджеви и Парк Сабира.",
            ],
          },
          {
            "title": "В отеле",
            "paragraphs": [
              "Хотите оставаться на связи? В отеле есть бесплатный Wi-Fi. Специально для автопутешественников организована парковка. Если планируете экскурсии, обратите внимание на экскурсионное бюро отеля. Для простоты передвижения возможна организация трансфера.",
              "А ещё в распоряжении гостей прачечная, химчистка, индивидуальная регистрация заезда и отъезда, гладильные услуги, прокат автомобилей и консьерж. Сотрудники отеля поддержат беседу на английском и русском.",
            ],
          },
          {
            "title": "В номере",
            "paragraphs": [
              "В номере вас будут ждать телевизор и мини-бар. Перечисленные услуги есть не во всех номерах.",
            ],
          },
        ],
        "front_desk_time_end": "00:00:00",
        "front_desk_time_start": "00:00:00",
        "metapolicy_extra_info":
            "<p>You'll be asked to pay the following charges at the property:</p> <ul><li>A tax is imposed by the city: EUR 0.61 per person, per night</li><li>Shuttle transfer per adult: EUR 25 (one-way)</li><li>Shuttle transfer per child: EUR 0 (one-way)</li> </ul> <p>We have included all charges provided to us by the property. </p><br /><br /><br /><ul>      <li>Airport shuttle fee: EUR 25 per vehicle (maximum occupancy 5)</li> <li>Airport shuttle fee per child: EUR 0 (up to 10 years old)</li>  <li>Self parking fee: EUR 5 per day</li>                       </ul> <p>The above list may not be comprehensive. Fees and deposits may not include tax and are subject to change. </p>",
        "is_gender_specification_required": false,
      },
    },
  ];
  final requestData = {
    "arrival": "Баку",
    "is_country": false,
    "nights_count": "3",
    "adults": "2",
    "book_day": "26",
    "book_month": "3",
    "book_year": "2025",
    "search_id": "",
    "telegram_id": "",
    "filter": {
      "stars": null,
      "services": [],
      "rg_ext": {},
      "hotel_city": [],
      "sortAsc": "1",
      "sortBy": "popular",
      "cost_min": "0",
      "cost_max": "100000000",
      "offset": 0,
      "limit": 10,
    },
  };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton.icon(
          onPressed: () async {
            const String apiKey = 'API_KEY'; // UUID4 format
            await init.initMapkit(apiKey: apiKey, locale: 'ru_RU');
            Navigator.push(
              context,
              MaterialPageRoute(
                builder:
                    (context) => MapkitFlutterApp(
                      data: resultMap,
                      isHotel: true,
                      requestData: requestData,
                    ),
              ),
            );
          },

          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF5CD8D2),
            foregroundColor: Colors.white,
            padding: EdgeInsets.symmetric(
              horizontal: 20,
              vertical: 12,
            ),
          ),
          icon: const Icon(Icons.map, color: Colors.white),
          label: Text(
            'Карта',
            style: TextStyle(fontSize: 14),
          ),
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
